status:
  state: online
spec:
  desired_state: online
  functions:
  - name: preprocess-data
    spec:
      verbose: false
      kind: job
      spec:
        entry_points:
          preprocess_data:
            name: preprocess_data
            has_varargs: false
            parameters:
            - name: context
            - name: file_path
              type: str
            lineno: 5
            doc: Preprocesa y registra datos en el Feature Store.
            has_kwargs: false
        default_handler: preprocess_data
        command: ''
        image: mlrun/mlrun
        disable_auto_mount: false
        build:
          origin_filename: preprocess.py
          functionSourceCode: aW1wb3J0IG1scnVuCmZyb20gc3RvcmV5IGltcG9ydCBNYXBDbGFzcwppbXBvcnQgcGFuZGFzIGFzIHBkCgpkZWYgcHJlcHJvY2Vzc19kYXRhKGNvbnRleHQsIGZpbGVfcGF0aDogc3RyKToKICAgICIiIlByZXByb2Nlc2EgeSByZWdpc3RyYSBkYXRvcyBlbiBlbCBGZWF0dXJlIFN0b3JlLiIiIgogICAgCiAgICAjIENhcmdhciBlbCBkYXRhc2V0CiAgICBkZiA9IHBkLnJlYWRfY3N2KGZpbGVfcGF0aCkKCiAgICAjIENvbnZlcnRpciBmZWNoYSB5IGhvcmEgYSBmb3JtYXRvIGRhdGV0aW1lCiAgICBkZlsiZmVjaGFfaG9yYSJdID0gcGQudG9fZGF0ZXRpbWUoZGZbImZlY2hhIl0gKyAiICIgKyBkZlsiaG9yYSJdKQoKICAgICMgRWxpbWluYXIgY29sdW1uYXMgb3JpZ2luYWxlcyBkZSBmZWNoYSB5IGhvcmEKICAgIGRmLmRyb3AoY29sdW1ucz1bImZlY2hhIiwgImhvcmEiXSwgaW5wbGFjZT1UcnVlKQoKICAgICMgRWxpbWluYXIgZmlsYXMgY29uIHZhbG9yZXMgbnVsb3MKICAgIGRmLmRyb3BuYShpbnBsYWNlPVRydWUpCgogICAgIyBGaWx0cmFyIHZhbG9yZXMgbmVnYXRpdm9zIGVuIGNvbnN1bW9fa3doIHkgY29zdGVfZXVyb3MKICAgIGRmID0gZGZbKGRmWyJjb25zdW1vX2t3aCJdID4gMCkgJiAoZGZbImNvc3RlX2V1cm9zIl0gPiAwKV0KCiAgICAjIE9idGVuZXIgZWwgcHJveWVjdG8gZGUgTUxSdW4KICAgIHByb2plY3QgPSBtbHJ1bi5nZXRfb3JfY3JlYXRlX3Byb2plY3QoInNtYXJ0Z3JpZHMiKQoKICAgICMgRGVmaW5pciBlbCBGZWF0dXJlIFN0b3JlCiAgICBmZWF0dXJlX3NldCA9IHByb2plY3QuZ2V0X2ZlYXR1cmVfc2V0KAogICAgICAgIG5hbWU9ImNvbnN1bW9fZWxlY3RyaWNvIiwKICAgICAgICBlbnRpdGllcz1bImNhc2FfaWQiLCAiZmVjaGFfaG9yYSJdLCAgIyBMbGF2ZXMgcHJpbWFyaWFzCiAgICAgICAgZGVzY3JpcHRpb249IkNvbnN1bW8gZWzDqWN0cmljbyBwb3IgY2FzYSB5IHRpZW1wbyIKICAgICkKCiAgICAjIEluZ2VyaXIgbG9zIGRhdG9zIGVuIGVsIEZlYXR1cmUgU3RvcmUKICAgIGZlYXR1cmVfc2V0LmluZ2VzdChkZikKCiAgICAjIEd1YXJkYXIgZGF0YXNldCBwcmVwcm9jZXNhZG8gZW4gUGFycXVldAogICAgY29udGV4dC5sb2dfZGF0YXNldCgiY29uc3Vtb19lbGVjdHJpY28iLCBkZj1kZiwgZm9ybWF0PSJwYXJxdWV0IikKCiAgICBwcmludCgi4pyFIERhdG9zIHByZXByb2Nlc2Fkb3MgeSBhbG1hY2VuYWRvcyBlbiBlbCBGZWF0dXJlIFN0b3JlLiIpCg==
          code_origin: https://github.com/hypergalois/SmartGridsAI#d87be78ecc2d6d3fd9cb731bcb68cd0b38797e1b:preprocess.py
        description: ''
        state_thresholds:
          pending_scheduled: 1h
          pending_not_scheduled: '-1'
          image_pull_backoff: 1h
          executing: 24h
      metadata:
        name: preprocess-data
        tag: latest
  default_image: ''
  goals: ''
  description: ''
  source: https://github.com/hypergalois/SmartGridsAI
  load_source_on_run: true
  artifact_path: s3://mlrun
kind: project
metadata:
  created: '2025-02-16T17:19:19.898000'
  name: smartgrids
