# Archivo: mlflow_deployment_template.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-model-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-model-server
  template:
    metadata:
      labels:
        app: mlflow-model-server
    spec:
      containers:
      - name: mlflow-model-server
        # Reemplaza "tu_usuario_dockerhub" por tu usuario real en Docker Hub.
        image: ikerlizarraga/mlflow-model-server:latest
        ports:
        - containerPort: 5000
        env:
        - name: MLFLOW_MODEL_URI
          value: "PLACEHOLDER_MODEL_URI"  # Línea clave: este valor se actualizará dinámicamente.
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-model-service
spec:
  selector:
    app: mlflow-model-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
